starting-city: "Atlanta"
max-outbreaks: 4
disease-cubes:
  - color: RED_CUBE
    count: 24
  - color: BLUE_CUBE
    count: 24
starting-number-of-cards: 2
default-infection-rate: 2
starting-infection-cards: 3 # TODO: 3 cubes first city, 2 cubes second, 1 last
epidemic-cards-player-deck: 4