# TODO: Unify cards in one Deck class that will have list of each card type.
game:
  number-of-outbreaks: 0
  starting-city: "Atlanta"
  max-outbreaks: 4
  disease-cubes:
    - color: RED_CUBE
      count: 4
    - color: BLUE_CUBE
      count: 4
  starting-number-of-cards: 4
  max-number-of-cards: 7
  default-infection-rate: 2
  cure-status:
    red: false
    blue: false